### ISSUE TITLE
Update build_db.py and fix path issue

### ISSUE THREAD

**Issue by isedwards** [opencdms/opencdms#320]
- [x] Separate the creation of the empty schema (`opencdmsdb.mapper_registry.metadata.create_all(engine)`) into a different script from loading data so that they can be done independently
- [x] Edit paths in [build_db.py](https://github.com/opencdms/opencdms/blob/515a9772d8c52e1f06582fdeb9b739b1f482e720/install/build_db.py#L73-L84) so that the `code_tables` and `data_tables` are relative to the location the script is being executed from (e.g. `with open(f"code_tables/{value}") as fh:`)
- [x] Update [build-database](https://github.com/opencdms/opencdms/blob/515a9772d8c52e1f06582fdeb9b739b1f482e720/docs/source/administrator/index.rst#build-database) instructions in Administrator documentation (e.g. `cd /tmp;
git clone ... ; cd opencdms-test-data/data/cdm/data; python3 /path/to/build_db.py`)
- [x] Build and deploy the docs (see [here](https://docs.opencdms.org/developer/docs/index.html))

**Comment by david-i-berry** [comment]
See https://github.com/opencdms/opencdms/pull/331

Docs still need updating. Paths now specified in environment variable.
